[app]
# The domain pointing to this server
domain = "public.commune.sh"
# The port the server will listen on
port = 8989

[appservice]
# ID of the appservice registration
id = "commune"
# sender_localpart from the appservice registration
sender_localpart = "public"
# The access token from the appservice registration
access_token = "app_service_access_token"
# The homeserver access token from the appservice registration
hs_access_token = "homeserver_access_token"

[appservice.rules]
# Will join every newly created room
auto_join = true
# Will only join if invited by user local to the room's homeserver
invite_by_local_user = true
# Restrict federated homeservers
# Leave empty to restrict all federated homeservers
# Example: ["matrix.org"]
# Use ["*"] to allow all federated homeservers
federation_domain_whitelist = ["matrix.org"]


[matrix]
# Local domain of the Synapse server
homeserver = "http://localhost:8008"
# The server_name part of your Synapse configuration
server_name = "commune.sh"

[redis]
address = "localhost:6379"
password = ""
rooms_db = 1
messages_db = 2
events_db = 3
state_db = 3

# Cache public rooms
[cache.public_rooms]
enabled = true
expire_after = 14400 # defaults to 4 hours if not set

# Cache all room state events
[cache.room_state]
enabled = true
expire_after = 3600 # defaults to 1 hour if not set

# Cache room messages
[cache.messages]
enabled = false
expire_after = 3600 # defaults to 1 hour if not set

[log]
max_size = 100
max_backups = 7
max_age = 30
compress = true
